# Generated by Django 4.1.3 on 2023-07-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
